# Generated by Django 4.2.1 on 2023-07-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mascotas', '0004_alter_productos_dv'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='precio',
            field=models.IntegerField(blank=True, default=0, verbose_name='Precio'),
            preserve_default=False,
        ),
    ]
